Develop
Slavawer/Exes14 pull request #17
Opened 2017-12-25 05:32 UTC by ilyaknyaz

2017-12-25 11:47 UTC, kasl requested changes
Ну и везде psr1/2 страдают

2017-12-25 11:47 UTC, kasl commented on app/Direction.php
> +
Можно выключить `timestamps` - они тут не нужны.

2017-12-25 11:47 UTC, kasl commented on app/Members.php
> +class Members extends Model
Ед число

2017-12-25 11:47 UTC, kasl commented on app/Members.php
> +        return $this->hasMany(Direction::class, 'direction_id');
А чо можно быть одновременно на нескольких направлениях?

2017-12-25 11:47 UTC, kasl commented on app/Members.php
> +    public function Direction()
с маленькой советуют в документации обзывать связи

2017-12-25 11:47 UTC, kasl commented on app/Members.php
> +class Members extends Model
И тоже не нужны timestamps

2017-12-25 11:47 UTC, kasl commented on app/Members.php
> +}
Где связь с поинтами?

2017-12-25 11:47 UTC, kasl commented on app/Points.php
> +class Points extends Model
А что со связями?

2017-12-25 11:47 UTC, kasl commented on database/migrations/2017_12_21_140927_create_direction_table.php
> +            $table->timestamps();
Не нужны

2017-12-25 11:47 UTC, kasl commented on database/factories/MembersFactory.php
> +    static $password;
Что за `static $password`?

2017-12-25 11:47 UTC, kasl commented on database/migrations/2017_12_21_141337_CreateMembersTable.php
> +            $table->string('info');
для info kучше использовать text, потому что описание может быть довольно большим.

2017-12-25 11:47 UTC, kasl commented on database/migrations/2017_12_21_141402_CreatePointsTable.php
> +         //   $table->integer('members_id')->unsigned()->default(1);
Зачем закомментированный код нужен?

2017-12-25 11:47 UTC, kasl commented on database/migrations/2017_12_21_140927_create_direction_table.php
> +            $table->string('title',255);
мне кажется нужен unique индеккс на поле title

2017-12-25 11:47 UTC, kasl commented on database/seeds/DirectionsSeeder.php
> +    public function run()
Сидер выполнит 5 запросовж. Зачем? Используй batch insert здесь

2017-12-25 11:47 UTC, kasl commented on database/seeds/MembersTableSeeder.php
> +        factory(App\Members::class, 10)->create();
Не соблюдено условие задачи:
> по два участника на каждое направление.

2017-12-25 11:47 UTC, kasl commented on database/seeds/PointsTableSeeder.php
> +            for ($m = 1; $m <= 10; $m++) {
Не надо так. Выбери прям из базы всех существующих участников и в `foreach` выдавай очки

2017-12-25 11:47 UTC, kasl commented on database/seeds/PointsTableSeeder.php
> +                $randomDate = date("d M Y", $timestamp);
Не надо мучений - используй faker

2017-12-25 11:47 UTC, kasl commented on database/migrations/2017_12_21_141838_ChangePointsTable.php
> +            $table->integer('members_id')->unsigned()->default(1);
Не должно быть никакого дефолтного значения. Это ж FK

2017-12-25 11:47 UTC, kasl commented on database/migrations/2017_12_21_141838_ChangePointsTable.php
> +            //
Миграция ломает консистентность БД. Напиши что-то в down. Когда ты делаешь down - миграция должна вернутьв тосостояние, в котором таблица была ДО up

2017-12-25 11:47 UTC, kasl commented on database/migrations/2017_12_21_141806_ChangeMembersTable.php
> +            //
Миграция ломает консистентность БД. Напиши что-то в down. Когда ты делаешь down - миграция должна вернутьв тосостояние, в котором таблица была ДО up

2017-12-25 11:47 UTC, kasl commented on database/migrations/2017_12_21_141402_CreatePointsTable.php
> +            $table->string('data');
Что за поле data? вроде не обсуждали такого

2017-12-26 06:22 UTC, kasl requested changes
Часть предыдущих комментариев проигнорирована

2017-12-26 06:22 UTC, kasl commented on app/Member.php
> +        return $this->hasMany(point::class, 'members_id', 'id');
Почему вдруг point с маленькой буквы?

2017-12-26 06:22 UTC, kasl commented on app/Member.php
> +        return $this->hasMany(point::class, 'members_id', 'id');
Куда делась связь с направлением?

2017-12-26 06:22 UTC, kasl commented on app/Point.php
> +        return $this->hasMany(member::class, 'members_id', 'id');
С большой буквы название класса

2017-12-26 06:22 UTC, kasl commented on app/Repositories/MembersRepository.php
> +    function getById($id, $column);
а зачем второй параметр? Метод наз-ся `getById`.

2017-12-26 06:22 UTC, kasl commented on app/Repositories/MembersRepository.php
> +interface MembersRepository
Почему какие-то методы начинаются с большой, а некоторые с маленькой буквы? Сделать согласно PSR

2017-12-26 06:22 UTC, kasl commented on app/Repositories/MembersRepository.php
> +interface MembersRepository
Где документация? Сейчас я не понимаю что должны делать эти методы, а соответственно и как-то комментировать их пока не буду

2017-12-26 06:22 UTC, kasl commented on database/factories/MembersFactory.php
> +        'status' => $faker->randomElement(['В игре', 'Выбыл']),
А где направление?

2017-12-26 06:22 UTC, kasl commented on database/factories/PointsFactory.php
> +        'points' => mt_rand(1, 5),
А где user_id ?

2017-12-26 06:22 UTC, kasl commented on database/migrations/2017_12_21_140927_create_direction_table.php
> +            $table->timestamps();
Я повторяю второй раз, надеюсь последний:
1) не нужны в этой таблице timestamps
2) нужен unique индекс на поле title

2017-12-26 06:22 UTC, kasl commented on database/migrations/2017_12_21_141337_CreateMembersTable.php
> +            $table->text('info', 200);
Зачем делать поле бОльшим, но ограничивать его 200 символами?

2017-12-26 06:22 UTC, kasl commented on database/migrations/2017_12_21_141402_CreatePointsTable.php
> +            $table->string('points');
кол-во очков будет десятичным значением

2017-12-26 06:22 UTC, kasl commented on database/seeds/DirectionsSeeder.php
> +    public function run()
Так и не исправлено

2017-12-26 06:22 UTC, kasl commented on database/seeds/MembersTableSeeder.php
> +        for ($i = 1; $i <= 5; $i++) {
Выбери прям из базы всех существующих участников и в foreach создавай участников

2017-12-26 06:22 UTC, kasl commented on database/seeds/PointsTableSeeder.php
> +        for ($i = 1; $i <= 10; $i++) {
Я уже писал как надо. Сделано не так.

> Выбери прям из базы всех существующих участников и в foreach выдавай очки

2017-12-26 07:25 UTC, ilyaknyaz commented on app/Repositories/MembersRepository.php
> +    function getById($id, $column);
Я задумывал его для вывода по id какого то одного участника

2017-12-26 07:53 UTC, kasl commented on app/Repositories/MembersRepository.php
> +    function getById($id, $column);
окей. Нормальная тема. Только второй то параметр зачем?

2018-01-04 11:10 UTC, closed without merging